# Generated by Django 3.2.7 on 2021-10-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEvaluaciones',
            fields=[
                ('idactividad_evaluaciones', models.AutoField(primary_key=True, serialize=False)),
                ('nro_repeticiones', models.IntegerField(blank=True, null=True)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('calificacion_aprobar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('idcurso', models.SmallAutoField(primary_key=True, serialize=False)),
                ('abrev_curso', models.CharField(db_collation='utf8mb3_swedish_ci', max_length=7)),
                ('codigo_curso', models.CharField(db_collation='utf8mb3_swedish_ci', max_length=15)),
                ('disponible_desde', models.DateField(null=True)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tipo_evaluacion', models.BooleanField(null=True)),
                ('fk_estatus_curso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estatus_curso', to='app.tablasconfiguracion')),
                ('fk_estruc_programa', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
                ('fk_tipo_duracion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_duracion', to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaEvaluacion',
            fields=[
                ('idescala_evaluacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('desc_escala', models.TextField()),
                ('maxima_puntuacion', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionesBloques',
            fields=[
                ('idevaluaciones_bloques', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_bloque', models.TextField(null=True)),
                ('comentario', models.TextField(null=True)),
                ('fk_actividad_evaluaciones', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.actividadevaluaciones')),
                ('fk_escala_bloque', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.escalaevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionesPreguntas',
            fields=[
                ('idevaluaciones_preguntas', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField(null=True)),
                ('puntos_pregunta', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('fk_evaluaciones_bloque', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.evaluacionesbloques')),
                ('fk_tipo_pregunta_evaluacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id_pagina', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(null=True)),
                ('ordenamiento', models.SmallIntegerField(null=True)),
                ('fk_estructura_programa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasOpciones',
            fields=[
                ('idpreguntas_opciones', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.TextField(null=True)),
                ('tipo_condicion', models.BooleanField(default=False)),
                ('puntos_porc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('path', models.TextField(null=True)),
                ('tipo_path', models.BooleanField(default=False)),
                ('compartido', models.BooleanField(default=False)),
                ('ordenamiento', models.SmallIntegerField(null=True)),
                ('fk_publico_autor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
                ('fk_tipo_recurso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('desc_tag', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecursos',
            fields=[
                ('idtipo_recurso', models.SmallAutoField(primary_key=True, serialize=False)),
                ('ruta_icono', models.TextField()),
                ('desc_recurso', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagRecurso',
            fields=[
                ('id_tag_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('fk_recurso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.recurso')),
                ('fk_tag', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.tag')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoPregunta',
            fields=[
                ('id_recurso_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('fk_pregunta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.evaluacionespreguntas')),
                ('fk_recurso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoPaginas',
            fields=[
                ('id_recurso_pagina', models.AutoField(primary_key=True, serialize=False)),
                ('fk_pagina', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.paginas')),
                ('fk_recurso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaProfesores',
            fields=[
                ('idprograma_profesores', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_autorizado', models.DateField(null=True)),
                ('fecha_retiro', models.DateField(null=True)),
                ('comentarios', models.TextField(null=True)),
                ('fk_estructura_programa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
                ('fk_publico', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
                ('fk_situacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionInstrucciones',
            fields=[
                ('idevaluacion_instrucciones', models.AutoField(primary_key=True, serialize=False)),
                ('texto_instrucciones', models.TextField(null=True)),
                ('fk_actividad_evaluaciones', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.actividadevaluaciones')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaCalificacion',
            fields=[
                ('idescala_calificacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('desc_calificacion', models.TextField()),
                ('puntos_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fk_calificacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
                ('fk_escala_evaluacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.escalaevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='CursosPrerequisitos',
            fields=[
                ('idcurso_prerequisitos', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fk_curso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.cursos')),
                ('fk_estruc_programa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadTarea',
            fields=[
                ('id_actividad_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField(null=True)),
                ('fk_estructura_programa', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadLeccion',
            fields=[
                ('id_actividad_leccion', models.AutoField(primary_key=True, serialize=False)),
                ('disponible_desde', models.DateField(null=True)),
                ('estatus', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
                ('fk_estructura_programa', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
            ],
        ),
        migrations.AddField(
            model_name='actividadevaluaciones',
            name='fk_escala_evaluacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.escalaevaluacion'),
        ),
        migrations.AddField(
            model_name='actividadevaluaciones',
            name='fk_estructura_programa',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma'),
        ),
        migrations.AddField(
            model_name='actividadevaluaciones',
            name='fk_tipo_duracion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividad_tipo_duracion', to='app.tablasconfiguracion'),
        ),
        migrations.CreateModel(
            name='ActividadConferencia',
            fields=[
                ('id_actividad_conferencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(null=True)),
                ('enlace', models.TextField(null=True)),
                ('clave', models.TextField(null=True)),
                ('id_conferencia', models.TextField(null=True)),
                ('fk_estructura_programa', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
                ('fk_publico', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
            ],
        ),
    ]
