# Generated by Django 3.2.7 on 2021-09-20 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalacalificacion',
            name='fk_escala_evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.escalaevaluacion'),
            preserve_default=False,
        ),
    ]
