# Generated by Django 3.2.7 on 2021-09-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210922_1556'),
        ('academic', '0002_escalacalificacion_fk_escala_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadevaluaciones',
            name='fk_escala_calificacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.escalacalificacion'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fk_categoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fk_estruc_programa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma'),
        ),
        migrations.AlterField(
            model_name='escalacalificacion',
            name='fk_calificacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion'),
        ),
        migrations.AlterField(
            model_name='escalacalificacion',
            name='fk_escala_evaluacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.escalaevaluacion'),
        ),
    ]
