# Generated by Django 3.2.7 on 2021-10-08 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratantesRol',
            fields=[
                ('idcontratantes_rol', models.AutoField(primary_key=True, serialize=False)),
                ('desc_rol', models.CharField(max_length=30)),
                ('fk_contratante', models.IntegerField()),
                ('valor_rol', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CtaUsuario',
            fields=[
                ('idcta_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('intentos_fallidos', models.IntegerField()),
                ('fecha_ult_cambio', models.DateField(blank=True, null=True)),
                ('respuesta_secreta', models.TextField(blank=True, null=True)),
                ('dias_cambio', models.IntegerField()),
                ('fk_pregunta_secreta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta', to='app.tablasconfiguracion')),
                ('fk_rol_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_usuario', to='app.tablasconfiguracion')),
                ('fk_status_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cuenta', to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='LandPage',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('fk_ciudad', models.SmallIntegerField(null=True)),
                ('direccion', models.TextField()),
                ('correos', models.TextField()),
                ('motivo_solicitud', models.TextField()),
                ('status_solicitud', models.BooleanField(default=False)),
                ('codigo_aprobacion', models.IntegerField(null=True)),
                ('fecha_solicitud', models.DateField(auto_now_add=True, null=True)),
                ('fec_cod_expiracion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSeguridad',
            fields=[
                ('idlog_seguridad', models.AutoField(primary_key=True, serialize=False)),
                ('fk_cta_usuario', models.SmallIntegerField()),
                ('fecha_transaccion', models.DateField()),
                ('fk_tipo_operacion', models.SmallIntegerField()),
                ('valor_dato', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CtaUsuario', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.ctausuario')),
                ('Publico', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
