# Generated by Django 3.2.7 on 2021-09-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicaciones',
            fields=[
                ('idaplicaciones', models.SmallAutoField(primary_key=True, serialize=False)),
                ('desc_aplicaciones', models.TextField()),
                ('cod_aplicacion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AplicacionesContratante',
            fields=[
                ('idaplicaciones_contratante', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fk_contratante', models.SmallIntegerField()),
                ('fk_aplicacion', models.SmallIntegerField()),
                ('cod_status_apli_contrat', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contratantes',
            fields=[
                ('idcontratantes', models.SmallAutoField(primary_key=True, serialize=False)),
                ('siglas', models.TextField(blank=True, null=True)),
                ('nombre_contratante', models.TextField()),
                ('apellido_contratante', models.TextField(blank=True, null=True)),
                ('rif_contratante', models.CharField(max_length=20)),
                ('slogan', models.TextField(blank=True, null=True)),
                ('codigo_contrato', models.TextField(blank=True, null=True)),
                ('fecha_contrato', models.DateField(blank=True, null=True)),
                ('mes_inicio_ejerc_fiscal', models.IntegerField()),
                ('direccion', models.TextField()),
                ('paginas_web', models.TextField()),
                ('correos', models.TextField()),
                ('telefonnos', models.TextField()),
                ('nombre_comercial', models.TextField()),
                ('personas_contacto', models.TextField(blank=True, null=True)),
                ('representante_legal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivelesprog',
            fields=[
                ('idprogniveles', models.SmallAutoField(primary_key=True, serialize=False)),
                ('programa', models.TextField()),
                ('proceso', models.TextField()),
                ('unidad', models.TextField()),
                ('curso', models.TextField()),
                ('topico', models.TextField()),
                ('actividad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('idpartner', models.AutoField(primary_key=True, serialize=False)),
                ('fk_relacion', models.SmallIntegerField()),
                ('fk_publico', models.IntegerField()),
                ('fk_sitaucion_relacion', models.SmallIntegerField()),
                ('datos_partner', models.TextField(blank=True, null=True)),
                ('paginas_web', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programascap',
            fields=[
                ('idprogramascap', models.AutoField(primary_key=True, serialize=False)),
                ('desc_programas', models.TextField()),
                ('objetivo', models.TextField()),
                ('alcance', models.TextField()),
                ('fecha_apertura', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('idpublico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('direccion', models.TextField()),
                ('procedencia', models.CharField(max_length=1)),
                ('docto_identidad', models.TextField()),
                ('fk_ciudad', models.SmallIntegerField()),
                ('correos', models.TextField()),
                ('telefonos', models.TextField()),
                ('fk_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contratantes')),
            ],
        ),
        migrations.CreateModel(
            name='TablasConfiguracion',
            fields=[
                ('id_tabla', models.SmallAutoField(primary_key=True, serialize=False)),
                ('desc_elemento', models.CharField(blank=True, max_length=70, null=True)),
                ('tipo_elemento', models.CharField(blank=True, max_length=1, null=True)),
                ('permite_cambios', models.IntegerField()),
                ('valor_elemento', models.TextField(blank=True, null=True)),
                ('mostrar_en_combos', models.IntegerField(blank=True, null=True)),
                ('maneja_lista', models.IntegerField(blank=True, null=True)),
                ('fk_tabla_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='PublicoRelacion',
            fields=[
                ('idpublico_rol', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fk_publico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
                ('fk_relacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='Estructuraprograma',
            fields=[
                ('idestructuraprogrmas', models.SmallAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('peso_creditos', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fk_estructura_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
            ],
        ),
    ]
