# Generated by Django 3.2.7 on 2021-09-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publico',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
    ]
