# Generated by Django 3.2.7 on 2021-09-22 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_publico_fecha_registro'),
    ]

    operations = [
           migrations.AddField(
           model_name='publico',
           name='user',
           field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estructuraprograma',
            name='fk_estructura_padre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma'),
        ),
        migrations.AlterField(
            model_name='publico',
            name='fk_contratante',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contratantes'),
        ),
        migrations.AlterField(
            model_name='publicorelacion',
            name='fk_publico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publico'),
        ),
        migrations.AlterField(
            model_name='publicorelacion',
            name='fk_relacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion'),
        ),
        migrations.AlterField(
            model_name='tablasconfiguracion',
            name='fk_tabla_padre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion'),
        ),
    ]
