# Generated by Django 3.2.7 on 2021-10-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaAlumnos',
            fields=[
                ('idmatricula_alumnos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateField()),
                ('fecha_aprobada', models.DateField(null=True)),
                ('origenSolicitud', models.SmallIntegerField(default=0)),
                ('fk_estruc_programa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
                ('fk_publico', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
                ('fk_status_matricula', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='app.tablasconfiguracion')),
                ('fk_tipo_matricula', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='PreciosFormacion',
            fields=[
                ('idprograma_precios', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, default=None, max_digits=11, null=True)),
                ('PorcentajeDescuento', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('fecha_habilitado', models.DateField(default=None, null=True)),
                ('fk_estruc_programa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='app.estructuraprograma')),
                ('fk_tipo_moneda', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculasPagos',
            fields=[
                ('idmatricula_pagos', models.AutoField(primary_key=True, serialize=False)),
                ('fk_metodopago_id', models.SmallIntegerField(default=None, null=True)),
                ('monto_cancel', models.DecimalField(decimal_places=2, default=None, max_digits=11, null=True)),
                ('fecha_pago', models.DateField(null=True)),
                ('referencia', models.CharField(blank=True, max_length=70, null=True)),
                ('codigo_hash', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('url_imagen', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('fk_matricula_alumnos', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idreferencia', to='registration.matriculaalumnos')),
                ('fk_tipomoneda', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.preciosformacion')),
                ('status_pay', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
    ]
