# Generated by Django 3.2.7 on 2021-09-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreciosFormacion',
            fields=[
                ('idprograma_precios', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('fk_estruc_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
                ('fk_tipo_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaAlumnos',
            fields=[
                ('idmatricula_alumnos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateField()),
                ('fk_estruc_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma')),
                ('fk_publico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
                ('fk_status_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='app.tablasconfiguracion')),
                ('fk_tipo_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='app.tablasconfiguracion')),
            ],
        ),
    ]
