# Generated by Django 3.2.7 on 2021-09-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaalumnos',
            name='fecha_aprobada',
            field=models.DateField(null=True),
        ),
    ]
