# Generated by Django 3.2.7 on 2021-09-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210922_1556'),
        ('registration', '0002_matriculaalumnos_fecha_aprobada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaalumnos',
            name='fk_estruc_programa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma'),
        ),
        migrations.AlterField(
            model_name='matriculaalumnos',
            name='fk_publico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publico'),
        ),
        migrations.AlterField(
            model_name='matriculaalumnos',
            name='fk_status_matricula',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='app.tablasconfiguracion'),
        ),
        migrations.AlterField(
            model_name='matriculaalumnos',
            name='fk_tipo_matricula',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='app.tablasconfiguracion'),
        ),
        migrations.AlterField(
            model_name='preciosformacion',
            name='fk_estruc_programa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estructuraprograma'),
        ),
        migrations.AlterField(
            model_name='preciosformacion',
            name='fk_tipo_moneda',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion'),
        ),
    ]
