# Generated by Django 3.2.7 on 2021-09-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', models.SmallAutoField(primary_key=True, serialize=False)),
                ('deescripcion', models.TextField()),
                ('desc_corta', models.TextField()),
                ('fk_rama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciasReq',
            fields=[
                ('idcompetenciasreq', models.AutoField(primary_key=True, serialize=False)),
                ('desc_competencia', models.TextField()),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_nivel', to='app.tablasconfiguracion')),
                ('fk_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.perfil')),
                ('fk_tipo_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
        ),
    ]
