# Generated by Django 3.2.7 on 2021-10-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', models.SmallAutoField(primary_key=True, serialize=False)),
                ('deescripcion', models.TextField()),
                ('desc_corta', models.TextField()),
                ('fk_rama', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
            options={
                'ordering': ['-idperfil'],
            },
        ),
        migrations.CreateModel(
            name='CompetenciasReq',
            fields=[
                ('idcompetenciasreq', models.AutoField(primary_key=True, serialize=False)),
                ('desc_competencia', models.TextField()),
                ('fk_nivel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencias_nivel', to='app.tablasconfiguracion')),
                ('fk_perfil', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.perfil')),
                ('fk_tipo_competencia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
            options={
                'ordering': ['-idcompetenciasreq'],
            },
        ),
        migrations.CreateModel(
            name='CompetenciasAdq',
            fields=[
                ('idcompetencias_adq', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=15)),
                ('experiencia', models.SmallIntegerField()),
                ('fk_competencia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencia', to='planning.competenciasreq')),
                ('fk_nivel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel', to='app.tablasconfiguracion')),
                ('fk_publico', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
                ('fk_tipo_duracion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion')),
            ],
            options={
                'ordering': ['-idcompetencias_adq'],
            },
        ),
    ]
