# Generated by Django 3.2.7 on 2021-09-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210922_1556'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciasreq',
            name='fk_nivel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencias_nivel', to='app.tablasconfiguracion'),
        ),
        migrations.AlterField(
            model_name='competenciasreq',
            name='fk_perfil',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.perfil'),
        ),
        migrations.AlterField(
            model_name='competenciasreq',
            name='fk_tipo_competencia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fk_rama',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablasconfiguracion'),
        ),
    ]
